export enum ErrorCodeEnum {
  USER_MISSING = "USER_MISSING",
  WRONG_PASSWORD = "WRONG_PASSWORD",
  EMAIL_EXIST = "EMAIL_EXIST",
  RECORD_EXIST = "RECORD_EXIST",
  OPEN_QUESTIONS_DOES_NEED_CHOICE = "OPEN_QUESTIONS_DOES_NEED_CHOICE",
  QUESTION_CHOICES_MUST = "QUESTION_CHOICES_MUST",
}
